### ISSUE TITLE
expected difference between our and gsl dilog

### ISSUE THREAD

**Issue by wkotlarski** [FlexibleSUSY/FlexibleSUSY#329]
@Expander, what difference would you expect between your dilog and the one from gsl? I've rewritten Felix's code for Barr-Zee contributions to g-2 to use your dilog instead of gsl's and the relative difference seems to be around 1e-5.

**Comment by Expander** [comment]
Interesting! Can you please print out the arguments that you pass to the function?

From my tests I've seen deviations
* in GSL of the order of 2*epsilon for the real dilog
* in GSL of the order of 10*epsilon for the complex dilog
* in polylogarithm of the order of 2*epsilon for the real dilog
* in polylogarithm of the order of 2*epsilon for the complex dilog

**Comment by wkotlarski** [comment]
I do see relative differences up to 1e-9. for arguments close to 0. E.g., for `z = (-1.08371e-08,1.32716e-24)` the real part differs by `2.7e-09`.

**Comment by Expander** [comment]
Many thanks! Here are the results from the polylogarithm library, GSL and the expected value:
~~~
PL:  (-1.08371e-08,1.32716e-24),                       diff = (-2.9360684852702336e-17,7.1912828517751373e-33)
GLS: (-1.0837099970639315e-08,1.3271619755126847e-24), diff = (0,1.9827039676045148e-30)
exp: (-1.0837099970639315e-08,1.3271599928087171e-24), diff = (0,0)
~~~
So, the difference is below the machine epsilon, but still non-zero.

The reason for the larger difference from the polylogarithm library is from the line:
~~~.cpp
   const double nz = norm_sqr(z);

   if (nz < std::numeric_limits<double>::epsilon()) {
      return z_;
   }
~~~
Since z^2 is below the machine epsilon, the routine returns simply z. This is plausible from the series expansion of the dilogarithm, where the next higher-order term is z^2/2, which is below the machine epsilon.

Anyway, I have to look a bit closer into this ...

**Comment by Expander** [comment]
I've prepared a solution and will fix it soon.

**Comment by Expander** [comment]
I've pushed a fix to address the issue.

**Comment by Expander** [comment]
BTW, many thanks for finding this issue! :)

**Comment by wkotlarski** [comment]
Glad to help. This sadly doesn't solve my problem as it's some deeper problem with Felix's code. I'll make a proper, new issue once I identify it.
